---
title: "Principal Components Analysis (PCA)"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Principal Components Analysis (PCA)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Rubrary)
library(dplyr)

# For `palmerpenguins` install
r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)
```

# Data

Using `palmerpenguins` dataset [from Allison Horst](https://allisonhorst.github.io/palmerpenguins/).

## Load data

Get `palmerpenguins` data and add a unique ID per entry.
```{r Get palmerpenguins data, message=FALSE}
if (!requireNamespace("palmerpenguins", quietly = TRUE)){
  install.packages("palmerpenguins")
}
library(palmerpenguins)

names(penguins)
data("penguins")
penguins <- penguins %>%
  as.data.frame() %>%
  mutate(Sample_ID = paste0(penguins_raw$`Individual ID`, "_", penguins_raw$`Sample Number`))
  
rownames(penguins) <- penguins$Sample_ID
```

## Run PCA

Subset data to numeric only, then run PCA.
```{r Run PCA, fig.width=6, fig.height=4}
num <- penguins %>%
  dplyr::select(!c(species, island, sex, year, Sample_ID)) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::select(where(~!all(is.na(.x)))) # Filter out NAs
  
pca <- Rubrary::run_PCA(
  df = num,
  summary = T, tol = 0,
  center = T, scale = T,
  screeplot = T
)
```

## Plot PCA

Use resulting `prcomp` object to plot PCA scores while annotating by `species` metadata.
```{r Plot PCA w/ species anno, fig.width=6, fig.height=4}
Rubrary::plot_PCA(
  df_pca = pca,
  anno = penguins,
  annoname = "Sample_ID",
  annotype = "species",
  title = "Palmer Penguins PCA Scores - Species",
  label = FALSE,
  density = T
)
```

Same PCA scores plot, but annotating by `sex` metadata.
```{r Plot PCA w/ sex anno, fig.width=6, fig.height=4}
Rubrary::plot_PCA(
  df_pca = pca,
  anno = penguins,
  annoname = "Sample_ID",
  annotype = "sex",
  title = "Palmer Penguins PCA Scores - Sex",
  label = FALSE,
  density = T
)
```

